version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dev1234
      POSTGRES_USER: dev
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./resources/postgres:/var/lib/postgresql/data
